stages:
  - deploy

deploy:
  tags:
    - runner
  stage: deploy
  script:
    - pwd
    - mvn clean package
    - docker-compose down
    - docker build -t test-project:1.0  .
    - docker-compose up -d


